services:
  helix-viewer:
    image: ghcr.io/adman234/helix-viewer:latest
    container_name: helix-viewer
    ports:
      - "7860:80"
    volumes:
      - ./uploads:/uploads
    restart: unless-stopped
